# Generated by Django 6.0.3 on 2026-03-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='characters',
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='air_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
